# Generated by Django 4.2.5 on 2023-09-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=255)),
                ('passport_expiry', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_info', models.JSONField()),
                ('fares_info', models.JSONField()),
                ('baggage_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.UUIDField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('birth_date', models.DateField()),
                ('passenger_category', models.CharField(max_length=255)),
                ('passenger_type', models.CharField(choices=[('ADT', 'ADULT'), ('CHD', 'CHILD'), ('INF', 'INFANT'), ('INS', 'INFANT_WITH_SEAT')])),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('document', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.document')),
                ('offer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('primary_key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('gds_pnr', models.CharField(max_length=255)),
                ('supplier_pnr', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('B', 'STATUS_BOOK'), ('T', 'STATUS_TICKET'), ('V', 'STATUS_VOID'), ('R', 'STATUS_REFUND'), ('E', 'STATUS_BOOK_ERROR'), ('C', 'STATUS_TICKET_ERROR'), ('O', 'STATUS_PAID_WAIT'), ('G', 'STATUS_IN_PROGRESS'), ('W', 'STATUS_VOID_ERROR'), ('F', 'STATUS_REFUND_ERROR')], default='B', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('ticket_time_limit', models.DateTimeField()),
                ('void_time_limit', models.IntegerField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('offer', models.JSONField()),
                ('provider', models.JSONField()),
                ('airline_code', models.CharField(max_length=300)),
                ('passengers', models.ManyToManyField(to='orders.passenger')),
            ],
            options={
                'ordering': ['-primary_key'],
            },
        ),
    ]
